---
#If this is false mobs will not register through VanillaX plugin
mobs: true

#Anything listed here, would not be registered from this plugin.
#If you would like all of these to be registered, delete the disabled section from the config.yml
#item. or you would want enchantments to be registered, but other to not be registered,
#simpily delete the enchantments section and you should be set.
disabled:
#  #Mobs includes armor stand, zombies, etc.
#  mobs:
#    - "minecraft:blaze" #this would be blaze entity Id
#
#  #List of blocks that wont be registered
  blocks:
#    - 145 #This would be anvil block Id
#
#  #Items includes Firework, Armor Stand and so on
#  items:
#    - 513 #This would be shield item Id
#
#  #Commands that wont be registered, they must be all lowercase.
  commands:
#    - "gamerule"
#
#  #Enchantments that wont be register
#  enchantments:
#    - 25 #ID of the Frost Walker Enchantment

#Features you can disable
features:
  #Disables weather including /weather
  weather: true
  #Disables gamerule and removes command /gamerule
  gamerule: true

#if this is true and gamerule feature is off, it will delete previous game rule from the world data.
gamerule-remove-cache: true
...